### ISSUE TITLE
run 'make test-all',the following error occurs

### ISSUE THREAD

**Issue by Zhanghongtao2417** [storaged-project/libblockdev#749] opened 2022-06-15 02:32 UTC
======================================================================
ERROR: test_mount_ntfs_ro (fs_test.MountTest)
Test mounting and unmounting read-only device with NTFS filesystem
----------------------------------------------------------------------
OSError: [Errno 16] Device or resource busy: '/tmp/libblockdev.3rbqwoxrmount_test'

======================================================================
ERROR: test_bcache_attach_detach (kbd_test.KbdTestBcacheAttachDetach)
Verify that it's possible to detach/attach a cache from/to a bcache device
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/libblockdev/libblockdev-2.26/libblockdev-master/libblockdev-2.26/tests/kbd_test.py", line 380, in test_bcache_attach_detach
    succ, dev = BlockDev.kbd_bcache_create(self.loop_dev, self.loop_dev2, None)
  File "/root/libblockdev/libblockdev-2.26/libblockdev-master/libblockdev-2.26/src/python/gi/overrides/BlockDev.py", line 445, in kbd_bcache_create
    return _kbd_bcache_create(backing_device, cache_device, extra)
gi.repository.GLib.GError: g-bd-kbd-error-quark: Failed to determine bcache device name for 'sdd' (4)

======================================================================

Is the environment or configuration incorrect? How should I fix it?

**Comment by vojtechtrefny** [comment] 2022-06-15 12:42
`test-all` runs all tests including those marked as "unstable". I'd recommend using just `make test` to run only "stable" tests. Unstable tests are randomly failing a we can't do nothing about that because the problem isn't in our code (or at least we think it isn't). Bcache is unfortunately notoriously broken. We are actually discussing removing the functionality in the next major version of libblockdev. The NTFS test case was removed in the latest release because it was testing ntfs-3g behaviour that changes between versions and also depends on some build time configuration that is different in different distributions. tl;dr you can ignore these failures.

**Comment by Zhanghongtao2417** [comment] 2022-06-16 06:15
Thank you for your reply， which solved my question.

**Closed** 2022-06-16 07:12 UTC
